### ISSUE TITLE
duplicate predicate

### ISSUE THREAD

**Issue by Nora-Olivia-Ammann** [dhlab-basel/JourneyStar#1]
The predicate trip-onto:hasLocation exists twice (correct one on 156). The property trip-onto:hasWikilink is already stated on line 355.

https://github.com/dhlab-basel/trip-ontology/blob/928912d67ea62cb5ebdafedb947be2518add10ce/tripOntology.ttl#L149C1-L153C84

**Comment by SepidehAlassi** [comment]
@Nora-Olivia-Ammann thanks for the heads up, it is fixed now!
