### ISSUE TITLE
Occurrence

### ISSUE THREAD

**Issue by Nora-Olivia-Ammann** [dhlab-basel/JourneyStar#10]
This is not wrong. But there is a class `trip-onto:Occurence` therefore it would seem intuitive to turn this into a `owl:ObjectProperty`. If that is true https://github.com/dhlab-basel/trip-ontology/blob/928912d67ea62cb5ebdafedb947be2518add10ce/tripOntology_shacl.ttl#L356 would need to be adapted.

https://github.com/dhlab-basel/trip-ontology/blob/928912d67ea62cb5ebdafedb947be2518add10ce/tripOntology.ttl#L285

**Comment by SepidehAlassi** [comment]
@Nora-Olivia-Ammann thanks for the heads up, it is fixed now!
