### ISSUE TITLE
trip-onto:meanOfTransportation

### ISSUE THREAD

**Issue by Nora-Olivia-Ammann** [dhlab-basel/JourneyStar#11]
This is declared as a `owl:DatatypeProperty`, however in the sample data it is exclusively used with resources.

https://github.com/dhlab-basel/trip-ontology/blob/928912d67ea62cb5ebdafedb947be2518add10ce/tripOntology.ttl#L304

**Comment by SepidehAlassi** [comment]
@Nora-Olivia-Ammann thanks for the heads up, it is fixed now!
