### ISSUE TITLE
usage of default prefix

### ISSUE THREAD

**Issue by Nora-Olivia-Ammann** [dhlab-basel/JourneyStar#12]
This comment is confusing as the default prefix is not declared and in the ontology the class with the label "Document" is called `trip-onto:Entry`.
https://github.com/dhlab-basel/trip-ontology/blob/928912d67ea62cb5ebdafedb947be2518add10ce/tripOntology.ttl#L344

**Comment by SepidehAlassi** [comment]
@Nora-Olivia-Ammann 
Same issue here. It seems like you accessed an old PR. As you can see above, your comment is on line 344 of the commit number 
`928912d`
 3 months ago, I corrected the mentioned issue of `tripOntology_Shacl.ttl`. Please see the main branch!

**Comment by SepidehAlassi** [comment]
@Nora-Olivia-Ammann thanks for the heads up, it is fixed now!
