### ISSUE TITLE
two Wikilink shapes

### ISSUE THREAD

**Issue by Nora-Olivia-Ammann** [dhlab-basel/JourneyStar#13]
I am confused why there are two shapes for has wiki link?

https://github.com/dhlab-basel/trip-ontology/blob/928912d67ea62cb5ebdafedb947be2518add10ce/tripOntology_shacl.ttl#L236
https://github.com/dhlab-basel/trip-ontology/blob/928912d67ea62cb5ebdafedb947be2518add10ce/tripOntology_shacl.ttl#L385

**Comment by SepidehAlassi** [comment]
@Nora-Olivia-Ammann 
It seems like you accessed an old PR. You can see that the line you have commented is not from main branch but from commit `928912d`!
3 months ago, this Shacl shapes file was updated, and the redundant shape was removed. Please have a look at the main branch.
