### ISSUE TITLE
owl:Property

### ISSUE THREAD

**Issue by Nora-Olivia-Ammann** [dhlab-basel/JourneyStar#2]
I cannot find a generic `owl:Property` in the ontology. All owl properties are `rdfs:subClassOf rdf:Property`, was this the intention?

https://github.com/dhlab-basel/trip-ontology/blob/928912d67ea62cb5ebdafedb947be2518add10ce/tripOntology.ttl#L249

**Comment by SepidehAlassi** [comment]
This is a typo, it must have been `owl:DatatypeProperty`
