### ISSUE TITLE
trip-onto:hasTransitFrom property type

### ISSUE THREAD

**Issue by Nora-Olivia-Ammann** [dhlab-basel/JourneyStar#4]
Based on the usage in the sample data this should be an `owl:ObjectProperty`

https://github.com/dhlab-basel/trip-ontology/blob/928912d67ea62cb5ebdafedb947be2518add10ce/tripOntology.ttl#L374

**Comment by SepidehAlassi** [comment]
@Nora-Olivia-Ammann thanks for the heads up, it is fixed now!
