### ISSUE TITLE
typo class is not capitalised

### ISSUE THREAD

**Issue by Nora-Olivia-Ammann** [dhlab-basel/JourneyStar#6]
`rdfs:subClassOf`

https://github.com/dhlab-basel/trip-ontology/blob/928912d67ea62cb5ebdafedb947be2518add10ce/tripOntology.ttl#L41

**Comment by SepidehAlassi** [comment]
@Nora-Olivia-Ammann 
In the IRI, the local identifier is capitalized
https://dbpedia.org/ontology/Place

the `dbo:Place` resolves to `https://dbpedia.org/ontology/Place` which is correct.
