### ISSUE TITLE
correct reference?

### ISSUE THREAD

**Issue by Nora-Olivia-Ammann** [dhlab-basel/JourneyStar#7]
The trip ontology seems to reference other related ontologies. The IRI `<http://ontology.eil.utoronto.ca/icity/Trip/activity>` does not seem to exist. Is this meant to be `<http://ontology.eil.utoronto.ca/icity/Activity/Activity>`

https://github.com/dhlab-basel/trip-ontology/blob/928912d67ea62cb5ebdafedb947be2518add10ce/tripOntology.ttl#L34

**Comment by SepidehAlassi** [comment]
@Nora-Olivia-Ammann thanks for the heads up, it is fixed now!
