### ISSUE TITLE
Capitalisation?

### ISSUE THREAD

**Issue by Nora-Olivia-Ammann** [dhlab-basel/JourneyStar#8]
Based on the IRI declared in the ontology `<http://ontology.eil.utoronto.ca/icity/Trip/Trip>` this may need to be capitalised.

https://github.com/dhlab-basel/trip-ontology/blob/928912d67ea62cb5ebdafedb947be2518add10ce/tripOntology.ttl#L50

**Comment by SepidehAlassi** [comment]
@Nora-Olivia-Ammann thanks for the heads up, it is fixed now!
