### ISSUE TITLE
Capitalisation?

### ISSUE THREAD

**Issue by Nora-Olivia-Ammann** [dhlab-basel/JourneyStar#9]
Same as previous: in original onto: `<http://ontology.eil.utoronto.ca/icity/Trip/Tour>`

https://github.com/dhlab-basel/trip-ontology/blob/928912d67ea62cb5ebdafedb947be2518add10ce/tripOntology.ttl#L65

**Comment by SepidehAlassi** [comment]
@Nora-Olivia-Ammann thanks for the heads up, it is fixed now!
